definitions:
  model.GlobalResponse:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  model.NewPost:
    properties:
      content:
        type: string
      title:
        type: string
    type: object
  model.NewUser:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  model.Post:
    properties:
      content:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    type: object
  model.PostMultipleResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/model.Post'
        type: array
      message:
        type: string
      success:
        type: boolean
    type: object
  model.PostResponse:
    properties:
      data:
        $ref: '#/definitions/model.Post'
      message:
        type: string
      success:
        type: boolean
    type: object
  model.TokenResponse:
    properties:
      message:
        type: string
      success:
        type: boolean
      token:
        type: string
    type: object
  model.UpdatePost:
    properties:
      content:
        type: string
      id:
        type: integer
      title:
        type: string
    type: object
  model.User:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      updated_at:
        type: string
    type: object
  model.UserData:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
  model.UserLogin:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  model.UserResponse:
    properties:
      data:
        $ref: '#/definitions/model.UserData'
      message:
        type: string
      success:
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a test API for Test Posting
  title: Test Posting API
  version: "1.0"
paths:
  /post:
    get:
      description: Return a single post by ID
      parameters:
      - description: Post ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.PostResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.PostResponse'
      summary: Show a post
      tags:
      - posts
  /post/create:
    post:
      consumes:
      - application/json
      description: Creates a new post with JSON input which includes the `title` and
        `content` fields
      parameters:
      - description: Post creation payload
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/model.NewPost'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.PostResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.PostResponse'
      summary: Create a new post
      tags:
      - posts
  /post/delete:
    delete:
      description: Deletes a post based on the `id` query parameter
      parameters:
      - description: Post ID to delete
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GlobalResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.GlobalResponse'
      summary: Delete a post by ID
      tags:
      - posts
  /post/update:
    put:
      consumes:
      - application/json
      description: Updates an existing post with JSON input containing `id`, `title`,
        and `content` fields
      parameters:
      - description: Post update payload
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/model.UpdatePost'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.PostResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.PostResponse'
      summary: Update an existing post
      tags:
      - posts
  /posts:
    get:
      description: returns a list of all posts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.PostMultipleResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.PostMultipleResponse'
      summary: Show all posts
      tags:
      - posts
  /user/login:
    post:
      consumes:
      - application/json
      description: Authenticate a user and return a token
      parameters:
      - description: User Login Payload
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TokenResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.TokenResponse'
      summary: User Login
      tags:
      - users
  /user/me:
    get:
      description: Returns the authenticated user's information
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.UserResponse'
      security:
      - BearerAuth: []
      summary: Get current user profile
      tags:
      - users
  /user/register:
    post:
      consumes:
      - application/json
      description: Register a use with name, email, and password
      parameters:
      - description: New User Payload
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.NewUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.GlobalResponse'
      tags:
      - users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
